#!/usr/bin/env bash
# governor_context.sh — pull top-K memories for the current scope and write
# them to a markdown file the agent harness will load as context.
#
# Usage:
#   governor_context.sh --target claude|opencode|codex|agents [--scope <path>] [--k 20] [--out <path>]
#   governor_context.sh --hook [--k 12]
#
# `--hook` is the Claude Code SessionStart mode: it recalls by *query* (the
# project name), not by scope filter — stored scope paths rarely match the
# cwd basename, which is why the scoped form returned nothing for months —
# and prints the memories as hookSpecificOutput.additionalContext JSON so
# Claude actually receives them (Claude Code never loads .claude/CONTEXT_MEMORY.md
# on its own). The markdown is also cached under
# ~/.local/state/agent-memory/context/<project>.md instead of inside the repo.
# Going through the Governor's /recall also records recall_stats, which is what
# the nightly dream sweep needs before it can promote anything.
#
# `agents` is the canonical agent-neutral target (writes to .agents/CONTEXT_MEMORY.md).
# `opencode` and `codex` are aliases for `agents`. `claude` writes to .claude/CONTEXT_MEMORY.md.
# New integrations should prefer `agents`.
#
# Exits 0 on empty recall; exits 0 on network error (degrade gracefully).

set -u

TARGET=""
SCOPE=""
K=20
OUT=""
TIMEOUT=2
HOOK=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGET="$2"; shift 2 ;;
    --scope)  SCOPE="$2";  shift 2 ;;
    --k)      K="$2";      shift 2 ;;
    --out)    OUT="$2";    shift 2 ;;
    --hook)   HOOK=1; TARGET="claude"; K=12; shift ;;
    -h|--help)
      sed -n '2,10p' "$0" >&2
      exit 0
      ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$TARGET" ]]; then
  echo "governor_context.sh: --target required" >&2
  exit 2
fi

# Load env from standard locations (first hit wins)
for f in "$HOME/.config/hippocampus.env" "$HOME/.config/agent-memory.env"; do
  if [[ -r "$f" ]]; then
    set -a
    # Runtime-selected env file; ShellCheck cannot resolve the path statically.
    # shellcheck disable=SC1090
    . "$f"
    set +a
    break
  fi
done

GOVERNOR_URL="${AGENT_MEMORY_GOVERNOR_URL:-${GOVERNOR_URL:-${HIPPOCAMPUS_URL:-http://127.0.0.1:54323}}}"
API_KEY="${AGENT_MEMORY_API_KEY:-${GOVERNOR_API_KEY:-${HIPPOCAMPUS_API_KEY:-}}}"
USER_ID="${AGENT_MEMORY_USER_ID:-${GOVERNOR_USER_ID:-ryer}}"

PROJECT="$(basename "$PWD")"
SCOPE="${SCOPE:-project:$PROJECT/user:$USER_ID}"
if [[ $HOOK -eq 1 ]]; then
  # Hook JSON on stdin carries cwd; prefer it over $PWD.
  HOOK_CWD="$(python3 -c 'import json,sys
try: print(json.load(sys.stdin).get("cwd") or "")
except Exception: print("")' 2>/dev/null)"
  [[ -n "$HOOK_CWD" ]] && PROJECT="$(basename "$HOOK_CWD")"
  QUERY="$PROJECT"
  REPO="$(git -C "${HOOK_CWD:-$PWD}" remote get-url origin 2>/dev/null | sed -E 's#.*[/:]([^/]+)/([^/]+?)(\.git)?$#\2#')"
  [[ -n "$REPO" && "$REPO" != "$PROJECT" ]] && QUERY="$PROJECT $REPO"
  OUT="${XDG_STATE_HOME:-$HOME/.local/state}/agent-memory/context/${PROJECT}.md"
fi

case "$TARGET" in
  claude)                  OUT="${OUT:-.claude/CONTEXT_MEMORY.md}" ;;
  agents|opencode|codex)   OUT="${OUT:-.agents/CONTEXT_MEMORY.md}" ;;
  *) echo "unknown --target: $TARGET" >&2; exit 2 ;;
esac

mkdir -p "$(dirname "$OUT")"

# Parse scope path into nested Scope JSON via a tiny Python helper.
SCOPE_JSON="$(python3 -c '
import json, sys
path = sys.argv[1]
segs = path.split("/")
scope = None
for kind, sid in reversed([s.split(":", 1) for s in segs]):
    scope = {"kind": kind, "id": sid, "parent": scope}
print(json.dumps(scope))
' "$SCOPE" 2>/dev/null)" || { echo "scope parse failed: $SCOPE" >&2; exit 0; }

if [[ $HOOK -eq 1 ]]; then
  REQ_BODY="$(QUERY="$QUERY" USER_ID="$USER_ID" K="$K" python3 -c 'import json,os
print(json.dumps({"user_id": os.environ["USER_ID"], "query": os.environ["QUERY"], "k": int(os.environ["K"]),
                  "filters": {"min_confidence": 0.5}}))')"
else
REQ_BODY="$(cat <<EOF
{
  "user_id": "$USER_ID",
  "query": "",
  "k": $K,
  "filters": {
    "scope": $SCOPE_JSON,
    "min_confidence": 0.5
  }
}
EOF
)"
fi

HDRS=(-H "Content-Type: application/json")
[[ -n "$API_KEY" ]] && HDRS+=(-H "X-API-Key: $API_KEY")

RESPONSE="$(curl -sS --max-time "$TIMEOUT" "${HDRS[@]}" \
  -X POST "$GOVERNOR_URL/recall" -d "$REQ_BODY" 2>/dev/null)" || {
  # Network failure: leave prior OUT in place
  exit 0
}

# Format results as a markdown bullet list with provenance comments.
FORMATTED="$(printf '%s' "$RESPONSE" | python3 -c '
import json, sys
try:
    data = json.loads(sys.stdin.read() or "{}")
except Exception:
    sys.exit(0)
results = data.get("results") or []
print("<!-- generated by governor_context.sh; scope='"$SCOPE"' -->")
print("# Relevant memory")
print()
print("> To search long-term memory on demand, run `agent-memory-search <query> [user_id] [limit]` (or legacy `sacred-search`). Defaults: `user_id=ryer,sam` (both assistant namespaces), `limit=5`. Use `user_id=david` for memories distilled from ChatGPT history. See `docs/AGENT_MEMORY_SEARCH.md` in the agent-memory repo.")
print()
if not results:
    print("_(no memories for this scope yet)_")
else:
    for r in results:
        text = (r.get("text") or "").strip().replace("\n", " ")
        kind = r.get("kind") or "?"
        conf = r.get("confidence")
        conf_str = f"{conf:.2f}" if isinstance(conf, (int, float)) else "?"
        disputed = " ⚠disputed" if r.get("disputed") else ""
        src = (r.get("provenance") or {}).get("source") or "?"
        print(f"- {text}  \n  <!-- kind={kind} conf={conf_str} src={src}{disputed} -->")
' 2>/dev/null)" || exit 0

printf '%s\n' "$FORMATTED" > "$OUT"

if [[ $HOOK -eq 1 ]]; then
  # Nothing recalled: stay silent rather than injecting an empty section.
  if printf '%s' "$FORMATTED" | grep -q '_(no memories for this scope yet)_'; then exit 0; fi
  FORMATTED="$FORMATTED" python3 -c 'import json,os
print(json.dumps({"hookSpecificOutput": {"hookEventName": "SessionStart",
                  "additionalContext": os.environ["FORMATTED"]}}))'
fi
exit 0
